// Generated by CoffeeScript 1.6.3
(function() {
  var twilio;

  twilio = require("twilio");

  twilio.initialize("ACe109988ea9b5503ec35864f6ff6b29ef", "1e2275664405bee94472737853e2c415");

  Parse.Cloud.define("sendTwilioMsg", function(request, response) {
    var number;
    number = request.params.number;
    return twilio.sendSMS({
      to: "+" + number,
      from: "+19177913141",
      body: request.params.message
    }, {
      success: function(httpResponse) {
        return response.success(number);
      },
      error: function(error, httpResponse) {
        return response.error(error, number);
      }
    });
  });

}).call(this);
