// Generated by CoffeeScript 1.6.3
(function() {
  var twilio;

  twilio = require("twilio");

  twilio.initialize("AC63d8a06d5b00148b5d6b76da58f3a3c7", "eadc01fbcf6742acf56eddbd9e811d32");

  Parse.Cloud.define("sendTwilioMsg", function(request, response) {
    var number;
    number = request.params.number;
    return twilio.sendSMS({
      to: "+" + number,
      from: "+15005550006",
      body: request.params.message
    }, {
      success: function(httpResponse) {
        return response.success(number);
      },
      error: function(error, httpResponse) {
        return response.error(error, number);
      }
    });
  });

}).call(this);
